### ISSUE TITLE
SIGSEGV on Maven Build

### ISSUE THREAD

**Issue by aewhite** [bramp/unsafe#2]
Output after after a fresh `git pull` and `mvn clean` and then `mvn`.
 
```
Running net.bramp.unsafe.UnrolledUnsafeCopierBuilderTest
#
# A fatal error has been detected by the Java Runtime Environment:
#
SUREFIRE-859: #  SIGSEGV (0xb) at pc=0x000000010d8fbedb, pid=6309, tid=4867
#
# JRE version: Java(TM) SE Runtime Environment (7.0_45-b18) (build 1.7.0_45-b18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.45-b08 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x2fbedb]  jni_GetObjectClass+0x83
#
SUREFIRE-859: # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/aewhite/Workspace/unsafe/unsafe-unroller/hs_err_pid6309.log
#
SUREFIRE-859: # If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#
/bin/sh: line 1:  6309 Abort trap: 6           /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/bin/java -jar /Users/aewhite/Workspace/unsafe/unsafe-unroller/target/surefire/surefirebooter530105423655139680.jar /Users/aewhite/Workspace/unsafe/unsafe-unroller/target/surefire/surefire8572191872144640609tmp /Users/aewhite/Workspace/unsafe/unsafe-unroller/target/surefire/surefire_08424476146213297588tmp
```

**Comment by bramp** [comment]
Would you attach the hs_err_pid6309.log please, and which OS is this? I've been using JDK 1.8.0_51 on MacOS, and 1.8.0_45 on Linux.

**Comment by aewhite** [comment]
I do not have an hs_err_pid*.log file. This is jdk1.7.0_45.jdk on OS X. I'll give JDK 8 a try in the AM.

**Comment by axemaster** [comment]
I am hitting his several times today. Just FYI, MBP Yosemite 10.10.5

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010b6d461c, pid=62468, tid=16643
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x3ce61c]  PhaseIdealLoop::idom_no_update(Node*) const+0x12
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

logs attached.
[files.tar.gz](https://github.com/bramp/unsafe/files/502069/files.tar.gz)

**Comment by bramp** [comment]
Thanks! What are you doing to trigger this? The crash appears to be in PhaseIdealLoop, which is not part of unsafe. A quick search, shows others reporting a similar crash: https://bugs.eclipse.org/bugs/show_bug.cgi?id=465693
